/*
 * Jobs in Finland
 *
 * API specification for Jobs in Finland API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lassi.patanen@gofore.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = JobsInFinland.Api.Infrastructure.CodeGen.Client.OpenAPIDateConverter;

namespace JobsInFinland.Api.Infrastructure.CodeGen.Model
{
    /// <summary>
    /// Transformations
    /// </summary>
    [DataContract(Name = "Transformations")]
    public partial class Transformations : IEquatable<Transformations>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Transformations" /> class.
        /// </summary>
        /// <param name="machineTranslated">machineTranslated.</param>
        /// <param name="machineHidden">machineHidden.</param>
        public Transformations(bool machineTranslated = default(bool), bool machineHidden = default(bool))
        {
            this.MachineTranslated = machineTranslated;
            this.MachineHidden = machineHidden;
        }

        /// <summary>
        /// Gets or Sets MachineTranslated
        /// </summary>
        [DataMember(Name = "machineTranslated", EmitDefaultValue = true)]
        public bool MachineTranslated { get; set; }

        /// <summary>
        /// Gets or Sets MachineHidden
        /// </summary>
        [DataMember(Name = "machineHidden", EmitDefaultValue = true)]
        public bool MachineHidden { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Transformations {\n");
            sb.Append("  MachineTranslated: ").Append(MachineTranslated).Append("\n");
            sb.Append("  MachineHidden: ").Append(MachineHidden).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Transformations);
        }

        /// <summary>
        /// Returns true if Transformations instances are equal
        /// </summary>
        /// <param name="input">Instance of Transformations to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Transformations input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MachineTranslated == input.MachineTranslated ||
                    this.MachineTranslated.Equals(input.MachineTranslated)
                ) && 
                (
                    this.MachineHidden == input.MachineHidden ||
                    this.MachineHidden.Equals(input.MachineHidden)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.MachineTranslated.GetHashCode();
                hashCode = (hashCode * 59) + this.MachineHidden.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
