name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore src/JobsInFinland.Api.Productizer
      - name: Build
        run: dotnet build src/JobsInFinland.Api.Productizer --no-restore
      - name: Publish
        run: dotnet publish src/JobsInFinland.Api.Productizer/JobsInFinland.Api.Productizer.csproj -c Release -o release --nologo
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: /home/runner/work/JobsInFinland.Api.Productizer/JobsInFinland.Api.Productizer/release/
          retention-days: 1
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN}}
      PULUMI_ORGANIZATION: virtualfinland
      PULUMI_STACK: dev
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./deployment/release/
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ env.PULUMI_STACK }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - name: Select Pulumi stack
        working-directory: ./deployment
        run: pulumi stack select ${{ env.PULUMI_ORGANIZATION}}/${{ env.PULUMI_STACK }} --create
      - name: Set artifact path
        working-directory: ./deployment
        run: pulumi config set artifactPath release/
      - name: Run Pulumi deployment
        working-directory: ./deployment
        run: pulumi up -y
